### PR TITLE
Added static inlining support

### LINKED ISSUE #9: Reduce the number of directories?
I'm not used to seeing header files in a separate "lib". Can we move them to the "src"?

I also wonder if the ptinit needs to be in it's own directory, and if it could go in the src with everything else.

### PR DESCRIPTION
**Pull request by singul4ri7y**
Added support to make the API functions static in `ptracer.h` header, so that the functions can be inlined if used in a single C/C++ translation with second order optimization and static linking. Improves performance although may introduce code redundancy across modules.

Resolves #9

### CODE REVIEW

**Comment by hugomg** [comment]
I thought extern was only for global variables, not functions?

If the performance of dynamically linked frameenter is so bad, there's not much point in even allowing it as an option. We should move frameenter/setline/frameleave out of the "implementation" and into the  ".h" part of the header file. Perhaps even define them as a macro, to guarantee that they are inlined.

**Comment by singul4ri7y** [comment]
The performance is bad, but not too bad that we should remove it. Besides, some modules may want to use dynamic version of Pallene Tracer. On top of that, the optimization mentioned is only applicable if you are using a single C file in entire module (just like Pallene does), which is sort of impractical if you are writing something heavyweight.

**Comment by hugomg** [comment]
I would expect that inlining the frameenter/setline/frameexit is probably a good idea even if we have many C files, since those are all one-liners.

**Review by hugomg — COMMENTED** [review]
(see comment)

**Review by hugomg — APPROVED** [review]

**Pull request merged**
